route:
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#5g-redteam-alerts'
    api_url: 'https://hooks.slack.com/services/TOKEN'
    send_resolved: true
    title: '{{ .CommonAnnotations.summary }}'
    text: |-
      *Alert:* {{ .CommonLabels.alertname }}
      *Severity:* {{ .CommonLabels.severity }}
      *Description:* {{ .CommonAnnotations.description }}
      *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
      *Dashboard:* <{{ .CommonAnnotations.dashboard_url }}|:bar_chart:>

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster']